name: Erro
description: Criar uma nova tarefa de erro.
labels: ["bug"]
body:
  - type: input
    id: related_issue_id
    attributes:
      label: Id Tarefa
      description: "Este erro tem relação com alguma tarefa? Se sim, indique o **id** da tarefa correspondente."
    validations:
      required: false
  - type: textarea
    id: bug_description
    attributes:
      label: Descrição
      description: Por favor, descreva o erro.
    validations:
      required: true
  - type: dropdown
    id: bug_severity
    attributes:
      label: Severidade
      description: "Qual o grau de severidade do erro? Indique 1 para Baixo, 2 para Médio e 3 para Alto."
      options:
        - 1 - Baixo
        - 2 - Médio
        - 3 - Alto
    validations:
      required: true
  - type: dropdown
    id: bug_estimation
    attributes:
      label: Estimativa (horas)
      description: Quantas horas você estima para resolver este erro? Escolha entre 1, 2, 3, 5 e 8 horas.
      options:
        - 1 hora
        - 2 horas
        - 3 horas
        - 5 horas
        - 8 horas
    validations:
      required: true
