name: Issue Report
description: File a feature report
title: "Issue Title"
body:
  - type: textarea
    id: issue_description
    attributes:
      label: Description
      description: Please, describe the issue.
    validations:
      required: true
  - type: dropdown
    id: issue_estimation
    attributes:
      label: Estimative (hours)
      description: How much hours do you estimate to finish this issue?
      options:
        - 1 hour
        - 2 hours
        - 3 hours
        - 5 hours
        - 8 hours
    validations:
      required: true
  - type: dropdown
    id: issue_complexity
    attributes:
      label: Complexity
      description: How complex is this issue?
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
  - type: dropdown
    id: issue_quality
    attributes:
      label: Quality
      description: With what quality was this issue solved?
      options:
        - Low
        - Medium
        - High
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
