name: Tarefa
description: Criar uma nova tarefa
labels: ['enhancement']
body:
  - type: textarea
    id: issue_description
    attributes:
      label: Descrição
      description: Por favor, descreva a tarefa.
    validations:
      required: true
  - type: dropdown
    id: issue_estimation
    attributes:
      label: Estimativa (horas)
      description: Quantas horas você estima para terminar esta tarefa?
      options:
        - 1 hora
        - 2 horas
        - 3 horas
        - 5 horas
        - 8 horas
    validations:
      required: true
  - type: dropdown
    id: issue_complexity
    attributes:
      label: Complexidade
      description: Quão complexa é esta tarefa?
      options:
        - Baixa
        - Média
        - Alta
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Métricas de Qualidade"
  - type: markdown
    attributes:
      value: "### O membro da equipe de qualidade que validar e verificar esta tarefa deve responder às questões a seguir."    
  - type: dropdown
    id: issue_legilibility
    attributes:
      label: Legilibidade
      description: O código escrito para resolver esta tarefa está legível? O código deve ser fácil de ler e entender, ter sintaxe clara, sem abreviações confusas e com um estilo de codificação consistente.
      options:
        - Baixa
        - Média
        - Alta
  - type: dropdown
    id: issue_simplicity
    attributes:
      label: Simplicidade
      description: O código escrito para resolver esta tarefa está simples e conciso?
      options:
        - Baixa
        - Média
        - Alta
  - type: dropdown
    id: issue_modularity
    attributes:
      label: Modularidade
      description: O código escrito para resolver esta tarefa está dividido em módulos ou funções independentes? Cada função ou módulo deve ter uma responsabilidade clara e bem definida.
      options:
        - Não se aplica
        - Baixa
        - Média
        - Alta
  - type: dropdown
    id: issue_confiability
    attributes:
      label: Confiabilidade
      description: O código escrito para resolver esta tarefa lida adequadamente com erros e exceções? As exceções devem retornar mensagens claras e informativas quando ocorrerem.
      options:
        - Não se aplica
        - Baixa
        - Média
        - Alta        
  - type: markdown
    attributes:
      value: "## Ao concluir o desenvolvimento desta tarefa, responda:"
  - type: textarea
    id: issue_not_finished_cause
    attributes:
      label: "Você terminou esta tarefa? Se não, por quê?"
      description: "Responda apenas se você **não** conseguiu terminar esta tarefa."
  - type: markdown
    attributes:
      value: "### Emoções"
  - type: input
    id: issue_emotions_affection
    attributes:
      label: Afeto
      description: Informe uma escala de 1 a 5 o quão fortemente sentiu esta emoção enquanto desenvolvia a tarefa. 1 = "Não senti", 5 = "Muito forte"
  - type: input
    id: issue_emotions_joy
    attributes:
      label: Alegria
      description: Informe uma escala de 1 a 5 o quão fortemente sentiu esta emoção enquanto desenvolvia a tarefa. 1 = "Não senti", 5 = "Muito forte"
  - type: input
    id: issue_emotions_optimism
    attributes:
      label: Otimismo
      description: Informe uma escala de 1 a 5 o quão fortemente sentiu esta emoção enquanto desenvolvia a tarefa. 1 = "Não senti", 5 = "Muito forte"
  - type: input
    id: issue_emotions_zest
    attributes:
      label: Entusiasmo
      description: Informe uma escala de 1 a 5 o quão fortemente sentiu esta emoção enquanto desenvolvia a tarefa. 1 = "Não senti", 5 = "Muito forte"
  - type: input
    id: issue_emotions_irritation
    attributes:
      label: Irritação
      description: Informe uma escala de 1 a 5 o quão fortemente sentiu esta emoção enquanto desenvolvia a tarefa. 1 = "Não senti", 5 = "Muito forte"
  - type: input
    id: issue_emotions_rage
    attributes:
      label: Raiva
      description: Informe uma escala de 1 a 5 o quão fortemente sentiu esta emoção enquanto desenvolvia a tarefa. 1 = "Não senti", 5 = "Muito forte"
  - type: input
    id: issue_emotions_sadness
    attributes:
      label: Tristeza
      description: Informe uma escala de 1 a 5 o quão fortemente sentiu esta emoção enquanto desenvolvia a tarefa. 1 = "Não senti", 5 = "Muito forte"
  - type: input
    id: issue_emotions_nervousness
    attributes:
      label: Nervosismo
      description: Informe uma escala de 1 a 5 o quão fortemente sentiu esta emoção enquanto desenvolvia a tarefa. 1 = "Não senti", 5 = "Muito forte"