name: Tarefa
description: Criar uma nova tarefa
labels: ['enhancement']
body:
  - type: textarea
    id: issue_description
    attributes:
      label: Descrição
      description: Por favor, descreva a tarefa.
    validations:
      required: true
  - type: dropdown
    id: issue_estimation
    attributes:
      label: Estimativa (horas)
      description: Quantas horas você estima para terminar esta tarefa?
      options:
        - 1 hora
        - 2 horas
        - 3 horas
        - 5 horas
        - 8 horas
    validations:
      required: true
  - type: dropdown
    id: issue_complexity
    attributes:
      label: Complexidade
      description: Quão complexa é esta tarefa?
      options:
        - Baixa
        - Média
        - Alta
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Ao concluir o desenvolvimento desta tarefa, responda:"
  - type: textarea
    id: issue_not_finished_cause
    attributes:
      label: "Você terminou esta tarefa? Se não, por quê?"
      description: "Responda apenas se você **não** conseguiu terminar esta tarefa."
  - type: markdown
    attributes:
      value: "### Emoções"
  - type: markdown
    attributes:
      value: "### Baseado na estrutura de emoções de Shaver et al. (acesso em https://doi.org/10.1037//0022-3514.52.6.1061)"    
  - type: dropdown
    id: issue_emotions_love
    attributes:
      label: Amor
      description: "Até que ponto você experimentou sentimentos de **amor** enquanto resolvia este problema? Exemplos de sentimentos relacionados ao amor: compaixão, carinho, afeto e excitação."
      options:
        - Nem um pouco
        - Ligeiramente
        - Moderadamente
        - Bastante
        - Extremamente
    validations:
      required: true
  - type: dropdown
    id: issue_emotions_joy
    attributes:
      label: Alegria
      description: "Até que ponto você experimentou sentimentos de alegria enquanto resolvia este problema? Exemplos de sentimentos relacionados a alegria: felicidade, satisfação, prazer, euforia, entusiasmo, otimismo e orgulho."
      options:
        - Nem um pouco
        - Ligeiramente
        - Moderadamente
        - Bastante
        - Extremamente
    validations:
      required: true
  - type: dropdown
    id: issue_emotions_anger
    attributes:
      label: Raiva
      description: "Até que ponto você experimentou sentimentos de raiva enquanto resolvia este problema? Exemplos de sentimentos relationados a raiva: agitação, frustração, ódio, indignação e inveja."
      options:
        - Nem um pouco
        - Ligeiramente
        - Moderadamente
        - Bastante
        - Extremamente
    validations:
      required: true
  - type: dropdown
    id: issue_emotions_sadness
    attributes:
      label: Tristeza
      description: "Até que ponto você experimentou sentimentos de tristeza enquanto resolvia este problema? Exemplos de sentimentos relationados a tristeza: angústia, tristeza, depressão, vergonha e insegurança."
      options:
        - Nem um pouco
        - Ligeiramente
        - Moderadamente
        - Bastante
        - Extremamente
    validations:
      required: true
  - type: dropdown
    id: issue_emotions_fear
    attributes:
      label: Medo
      description: "Até que ponto você experimentou sentimentos de medo enquanto resolvia este problema? Exemplos de sentimentos relationados ao medo: susto, pânico, nervosismo, ansiedade, aflição, preocupação e apreensão."
      options:
        - Nem um pouco
        - Ligeiramente
        - Moderadamente
        - Bastante
        - Extremamente
    validations:
      required: true