dename: Tarefa
description: Criar uma nova tarefa
body:
  - type: textarea
    id: issue_description
    attributes:
      label: Descrição
      description: Por favor, descreva a tarefa.
    validations:
      required: true
  - type: dropdown
    id: issue_estimation
    attributes:
      label: Estimativa (horas)
      description: Quantas horas você estima para terminar esta tarefa?
      options:
        - 1 hora
        - 2 horas
        - 3 horas
        - 5 horas
        - 8 horas
    validations:
      required: true
  - type: dropdown
    id: issue_complexity
    attributes:
      label: Complexidade
      description: Quão complexa é esta tarefa?
      options:
        - Baixa
        - Média
        - Alta
    validations:
      required: true
  - type: dropdown
    id: issue_quality
    attributes:
      label: Qualidade
      description: Com que qualidade essa tarefa foi resolvida?
      options:
        - Baixa
        - Média
        - Alta
  - type: markdown
    attributes:
      value: "## Ao concluir esta tarefa, responda:"
  - type: markdown
    attributes:
      value: "Responda a questão abaixo se você *não* conseguiu terminar a tarefa."
  - type: input
    attributes:
      label: "Por quê você não conseguiu termina-la?"
