name: Controle de Qualidade
description: Criar uma nova tarefa de controle de qualidade
labels: ['quality']
body:
  - type: input
    id: related_issue_id
    attributes:
      label: Id Tarefa
      description: Indique o id da tarefa correspondente, se houver.
    validations:
      required: false
  - type: textarea
    id: quality_description
    attributes:
      label: Descrição
      description: Por favor, descreva a tarefa.
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Métricas de Qualidade"
  - type: markdown
    attributes:
      value: "### O membro da equipe de qualidade que validar e verificar esta tarefa deve responder às questões a seguir."    
  - type: dropdown
    id: issue_legilibility
    attributes:
      label: Legilibidade
      description: O código escrito para resolver esta tarefa está legível? O código deve ser fácil de ler e entender, ter sintaxe clara, sem abreviações confusas e com um estilo de codificação consistente.
      options:
        - Baixa
        - Média
        - Alta
  - type: dropdown
    id: issue_simplicity
    attributes:
      label: Simplicidade
      description: O código escrito para resolver esta tarefa está simples e conciso?
      options:
        - Baixa
        - Média
        - Alta
  - type: dropdown
    id: issue_modularity
    attributes:
      label: Modularidade
      description: O código escrito para resolver esta tarefa está dividido em módulos ou funções independentes? Cada função ou módulo deve ter uma responsabilidade clara e bem definida.
      options:
        - Não se aplica
        - Baixa
        - Média
        - Alta
  - type: dropdown
    id: issue_confiability
    attributes:
      label: Confiabilidade
      description: O código escrito para resolver esta tarefa lida adequadamente com erros e exceções? As exceções devem retornar mensagens claras e informativas quando ocorrerem.
      options:
        - Não se aplica
        - Baixa
        - Média
        - Alta